consul:
  image: autopilotpattern/consul
  restart: always
  dns:
    - 127.0.0.1
  labels:
    - triton.cns.services=consul
  ports:
    - "8500:8500"
  command: >
    /usr/local/bin/containerpilot
    /bin/consul agent -server
      -config-dir=/etc/consul
      -log-level=err
      -bootstrap-expect 1
      -ui-dir /ui
prometheus:
    image: autopilotpattern/prometheus
    mem_limit: 128m
    restart: always
    ports:
      - "9090:9090"
    env_file:
      - _env
influx:
  image: autopilotpattern/influxdb
  restart: always
  env_file:
    - _env
  environment:
    - ADMIN_USER=root
    - INFLUXDB_INIT_PWD=root
    - INFLUXDB_REPORTING_DISABLED=true
    - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    - INFLUXDB_HTTP_LOG_ENABLED=false
    - INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED=false
serializer:
  image: d0cker/serializer:4.0.0
  env_file:
    - _env
  environment:
    - INFLUXDB_USER=root
    - INFLUXDB_PWD=root
  expose:
    - "80"
  restart: always
frontend:
  image: d0cker/frontend:4.0.0
  env_file:
    - _env
  ports:
    - "80:80"
  restart: always
  labels:
    - triton.cns.services=frontend
humidity:
  image: d0cker/sensor:1.0.0
  env_file:
    - _env
  environment:
    - SENSOR_TYPE=humidity
  restart: always
motion:
  image: d0cker/sensor:1.0.0
  env_file:
    - _env
  environment:
    - SENSOR_TYPE=motion
  restart: always
temperature:
  image: d0cker/sensor:1.0.0
  env_file:
    - _env
  environment:
    - SENSOR_TYPE=temperature
  restart: always
smartthings:
  image: d0cker/smartthings:4.0.0
  labels:
    - triton.cns.services=smartthings
  ports:
    - "80:80"
  environment:
    - PORT=80
  restart: always
